- name: Backup some file
  hosts: all
  become: yes
  tasks:
  - name: Check that the somefile exists
    stat:
      path: "{{file_path}}"
    register: stat_result
    
  - name: Create backup of some
    copy:
      remote_src: True
      src: "{{file_path}}"
      dest: "{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}-{{file_path}}.bak"
      backup: true
    when:  stat_result.stat.exists  
