- name: CloudHealth Agent Installation Helper
  hosts: all
  become: yes
  tasks:

    - name: Install wget on Debian
      apt:
         name: wget
         state: present
      when: ansible_pkg_mgr == "apt"
      
    - name: Install wget on CentOS
      block:
      - name: Install wget
        yum:
         name: wget
         state: present
      when: ansible_pkg_mgr == "yum"
    - name: Ensure the agent is installed
      command: wget https://s3.amazonaws.com/remote-collector/agent/v24/install_cht_perfmon.sh -O install_cht_perfmon.sh 
      args:
        creates: /opt/cht_perfmon 
      
    - name: Run sh script
      command: sh /tmp/install_cht_perfmon.sh 24 {{ cht_unique_registration_code }} aws
      args:
        creates: /opt/cht_perfmon




