- name: CloudHealth Agent Installation Helper
  hosts: all
  become: yes
  tasks:

    - name: Install wget on Debian
      apt:
         name: wget
         state: present
      when: ansible_distribution == "Debian"
      
    - name: Install wget on CentOS
      block:
      - name: Install wget
        dnf:
         name: wget
         state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and ansible_pkg_mgr == "yum"
    - name: Ensure the agent is installed
      command: wget https://s3.amazonaws.com/remote-collector/agent/v14/install_cht_perfmon.sh -O /tmp/install_cht_perfmon.sh 
      
    - name: Run sh script
      command: sh /tmp/install_cht_perfmon.sh 14 {{ cht_unique_registration_code }} aws
      args:
        creates: /opt/cht_perfmon




