- name: CloudHealth Agent Installation Helper
  hosts: all
  become: yes
  tasks:

    - name: Install wget on Debian
      apt:
         name: wget
         state: present
      when: ansible_distribution == "Debian"
      
    - name: Install wget on CentOS
      yum:
         name: wget
         state: present
      when: ansible_distribution == "CentOS" && ansible_distribution_major_version = "7" && ansible_pkg_mgr == "yum"


