- name: CloudHealth Agent Installation Helper
  hosts: all
  become: yes
  tasks:

    - name: Install wget on Debian
      apt:
         name: wget
         state: present
      when: ansible_distribution == "Debian"
      
    - name: Install wget on CentOS
      block:
      - name: Add repo
        yum_repository:
          name: from_ansible
          description: Repo add from ansible
          baseurl: https://centos.pkgs.org/$releasever/$basearch/
      - name: Add repository
        yum_repository:
          name: epel
          description: EPEL YUM repo
          baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

      - name: Add multiple repositories into the same file (1/2)
        yum_repository:
          name: epel
          description: EPEL YUM repo
          file: external_repos
          baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
          gpgcheck: no

      - name: Add multiple repositories into the same file (2/2)
        yum_repository:
          name: rpmforge
          description: RPMforge YUM repo
          file: external_repos
          baseurl: http://apt.sw.be/redhat/el7/en/$basearch/rpmforge
          mirrorlist: http://mirrorlist.repoforge.org/el7/mirrors-rpmforge
          enabled: no
      - name: Add repository
        yum_repository:
          name: CentOSPlus
          description: CentOSPlus YUM repo
          baseurl: http://mirror.centos.org/centos/$releasever/centosplus/$basearch/
      - name: Install wget
        yum:
         name: wget
         state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and ansible_pkg_mgr == "yum"
    - name: Ensure the agent is installed
      command:
        wget https://s3.amazonaws.com/remote-collector/agent/v14/install_cht_perfmon.sh -O /tmp/install_cht_perfmon.sh &&
        /tmp/install_cht_perfmon.sh 14 {{ cht_unique_registration_code }} aws
      args:
        creates: /opt/cht_perfmon




