- name: CloudHealth Agent Installation Helper
  hosts: all
  become: yes
  tasks:

    - name: Install wget package (Debian based)
      action: apt pkg='wget' state=installed
      only_if: "'$ansible_pkg_mgr' == 'apt'"

    - name: Install wget package (RedHat based)
      action: yum name='wget' state=installed
      only_if: "'$ansible_pkg_mgr' == 'yum'"

    - name: Wget CloudHealth agent
      command:
         wget https://s3.amazonaws.com/remote-collector/agent/v18/install_cht_perfmon.sh -O /tmp/install_cht_perfmon.sh 
      args:
        creates: /opt/cht_perfmon
    - name: Install the agent
      command: sh /tmp/install_cht_perfmon.sh 14 {{ cht_unique_registration_code }} aws
      args:
        creates: /opt/cht_perfmon

