- name: CloudHealth Agent Installation Helper
  hosts: all
  become: yes
  tasks:

    - name: Install wget on Debian
      apt:
         name: wget
         state: present
      when: ansible_distribution == "Debian"
      
    - name: Install wget on CentOS
      block:
      - name: Install  epel-release
        yum:
          name:  centos-release-scl
          state: present
      - name: Install wget
        yum:
         name: wget
         state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and ansible_pkg_mgr == "yum"




