- name: CloudHealth Agent Installation Helper
  hosts: all
  become: yes
  tasks:

    - name: Install wget on Debian
      apt:
         name: wget
         state: present
      when: ansible_distribution == "Debian"
      
    - name: Install wget on CentOS
      yum:
         name: wget
         state: present
      when: ansible_distribution == "CentOS"

    - name: Wget CloudHealth agent
      command:
         wget https://s3.amazonaws.com/remote-collector/agent/v18/install_cht_perfmon.sh -O /tmp/install_cht_perfmon.sh 
      args:
        creates: /opt/cht_perfmon
    - name: Install the agent
      command: sh /tmp/install_cht_perfmon.sh 14 {{ cht_unique_registration_code }} aws
      args:
        creates: /opt/cht_perfmon

