- name: Create user on a linux server
  hosts: all
  become: yes
  gather_facts: false
  tasks:
      - name: Create a login user
        user:
          name: "{{ user }}"
          password: "{{ password }}"

          state: present

      - name: Add public key to authorized_keys
        authorized_key:
          user: "{{ user }}"
          state: present
          key: "{{ add_authorized_key }}"
      
      - name: adding existing user '{{ user }}' to group sudo
        user:
          name: '{{ user }}'
          groups: sudo
          append: yes





