- name: Create user on a linux server
  hosts: all
  become: yes
  gather_facts: false
  tasks:
      - name: Check if {{ user }}  exist
        shell: "getent passwd {{ user }} > /dev/null 1&>1 ; echo $?"
        register: user_exist
      - name: debug
        debug:
          msg: " {{ user_exist }} "
      - name: create new user  
        block:
        - name: Create a login {{ user }} 
          user:
            name: "{{ user }}"
            password: "{{ password }}"
            state: present

        - name: Add public key to authorized_keys for {{ user }} 
          authorized_key:
            user: "{{ user }}"
            state: present
            key: "{{ add_authorized_key }}"
      
        - name: adding existing user '{{ user }}' to group sudo
          user:
            name: '{{ user }}'
            groups: sudo
            append: yes
          
        - name: Add {{ user }} to sudoers file
          ansible.builtin.lineinfile:
            path: /etc/sudoers
            regexp: '^{{ user }}'
            line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
            validate: 'visudo -cf %s'
        when: user_exist.stdout == "2"



