- name: Create user on a linux server
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Check if user exists
      getent:
        database: passwd
        key: '{{ user }}'
        #"{{ user_name }}"
        fail_key: False

   
    - name: Add new user - '{{ user }}'  
      user:
        name: '{{ user }}'
        shell: /sbin/nologin
        append: yes
        comment: '{{ description }}'
        state: present
      when: 
        - None in ansible_facts.getent_passwd.values()
        - '{{ user_shell }} == No'

    - name: Add new user - '{{ user }}'  
      user:
        name: '{{ user }}'
        append: yes
        comment: '{{ description }}'
        state: present
      when: 
        - None in ansible_facts.getent_passwd.values()
        - '{{ user_shell }} == Yes'
        
    - name: Add sudo rules
      block:
      - name: Add public key to authorized_keys for {{ user }} 
        authorized_key:
          user: "{{ user }}"
          state: present
          key: "{{ add_authorized_key }}"
      
      - name: adding existing user '{{ user }}' to group sudo
        user:
          name: '{{ user }}'
          groups: sudo
          append: yes
          
      - name: Add {{ user }} to sudoers file
        ansible.builtin.lineinfile:
          path: /etc/sudoers
          regexp: '^{{ user }}'
          line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
          validate: 'visudo -cf %s'
          
      when:
        -  None not in ansible_facts.getent_passwd.values() 
        - '{{ sudo_access }} == Yes'


