- name: Install nginx
  hosts: all
  become: yes
  tasks:
    - name: Install nginx on Debian
      apt:
         name: nginx
         state: present
      when: ansible_distribution == "Debian"
      
    - name: Install nginx on CentOS
      yum:
         name: nginx
         state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and ansible_pkg_mgr == "yum"

      
    - name: Check if user exists
      getent:
        database: passwd
        key: nginx
        #"{{ user_name }}"
        fail_key: False

   
    - name: Add user "nginx"  
      user:
        name: nginx
        shell: /sbin/nologin
        append: yes
        comment: "Nginx web server"
        state: present
      when: None in ansible_facts.getent_passwd.values()
       
    - name: Create dir with project 
      file:
        path: "/var/www/{{ ansible_hostname }}/html"
        state: directory
        owner: root
        group: root
        mode: 0775 
        
    - name: Copy index template
      template:
        src: ./index.j2
        dest: /var/www/{{ ansible_hostname }}/html/intex.html
        mode: 0644
        
    - name: Copy nginx config for Debian
      block:
      - name: Copy nginx config
        template:
          src: ./nginx.j2
          dest: /etc/nginx/sites-available/{{ ansible_hostname }}.conf
          mode: 0644

      - name: Create symbolic link
        file:
          src: "/etc/nginx/sites-available/{{ ansible_hostname }}.conf"
          dest: "/etc/nginx/sites-enabled/{{ ansible_hostname }}.conf"
          state: link
      when: ansible_distribution == "Debian"
        
    - name: Copy nginx config for Centos
      template:
        src: ./nginx.j2
        dest: /etc/nginx/conf.d/{{ ansible_hostname }}.conf
        mode: 0644
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and ansible_pkg_mgr == "yum"
      
    - name: Restart service nginx, in all cases
      ansible.builtin.service:
        name: nginx
        state: restarted
      
