- name: Install nginx
  hosts: all
  become: yes
  tasks:
    - name: Install nginx on Debian
      apt:
         name: nginx
         state: present
      when: ansible_distribution == "Debian"
      
    - name: Install nginx on CentOS
      yum:
         name: nginx
         state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and ansible_pkg_mgr == "yum"

      
    - name: Check if user exists
      getent:
        database: passwd
        key: nginx
        #"{{ user_name }}"
        fail_key: False

   
    - name: Add user "nginx"  
      user:
        name: nginx
        shell: /sbin/nologin
        append: yes
        comment: "Nginx web server"
        state: present
      when: None in ansible_facts.getent_passwd.values()
       
    - name: Create dir with project 
      file:
        path: "/var/www/{{ ansible_hostname }}/html"
        state: directory
        owner: nginx
        group: nginx
        mode: 0775 
        
    - name: Copy index template
      template:
        src: ./index.j2
        dest: /var/www/{{ ansible_hostname }}/html/intex.html
        mode: 0644
