- name: Install nginx
  hosts: all
  become: yes
  tasks:
    - name: Install nginx on Debian
      apt:
         name: nginx
         state: present
      when: ansible_distribution == "Debian"
      
    - name: Install nginx on CentOS
      yum:
         name: nginx
         state: present
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and ansible_pkg_mgr == "yum"
    
    - name: Create dir with project 
      file:
        path: "/var/www/{{ ansible_hostname }}/html"
        state: directory
        owner: nginx
        group: nginx
        mode: 0775 
