- name: Install mysql
  hosts: all
  become: yes

  tasks:
    - name: Add MySQL 8 ubuntu xenial repository
      apt_repository:
        repo: "deb http://repo.mysql.com/apt/debian/dists/bullseye/mysql-8.0/"
        state: present
      when: ansible_distribution == "Debian"
      
    - name: Install mysql on Debian
      apt:
        name:
          - mysql-server
          - mysql-devel
          - gcc
        state: latest
      when: ansible_distribution == "Debian"
  # - name: Run MYSQL commands
  # command: |
  #   mysql -p{{ mysql_root_password }} -ne "{{ item }}"
  # with_items:
  #   {{ mysql_root_password }}
