- name: Install mysql
  hosts: all
  become: yes

  tasks:
    - name: Run apt upgrade
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 432000
    - name: Add MySQL 8 Debian bullseye repository
      apt_repository:
        repo: deb http://repo.mysql.com/apt/debian/ bullseye mysql-apt-config
        state: present
        filename: mysql_8_0.list
        update_cache: no
      when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11"
    - name: Add apt key
      apt_key:
        keyserver: keyring.debian.org
        id: 467B942D3A79BD29
        state: present

    - name: Install mysql on Debian
      apt:
        name:
          - mysql-server
          - mysql-devel
          - gcc
        state: latest
      when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11"
  # - name: Run MYSQL commands
  # command: |
  #   mysql -p{{ mysql_root_password }} -ne "{{ item }}"
  # with_items:
  #   {{ mysql_root_password }}
