- name: Install mysql
  hosts: all
  become: yes

  tasks:
    - name: mysql | Install MySQL Packages
      apt:
        pkg: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - mysql-server
        - mysql-client

    - name: Install mysql on Debian
      apt:
        name:
          - mysql-server
          - mysql-devel
          - gcc
        state: latest
      when: ansible_distribution == "Debian"
  # - name: Run MYSQL commands
  # command: |
  #   mysql -p{{ mysql_root_password }} -ne "{{ item }}"
  # with_items:
  #   {{ mysql_root_password }}
