- name: Install mysql
  hosts: all
  become: yes

  tasks:
    - name: Install, configure, and start MySQL 8 on Debian 11
      block:
        - name: Install gnupg
          apt:
            name: gnupg
            state: latest
          when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11"
        - name: Download mysql-apt-config_0.8.22-1_all.deb to tmp
          get_url:
            url: "https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb"
            dest: "/tmp"
          #when: mysql-apt-config_0.8.22-1_all.deb.rc == 1
      when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11"
