- name: Install mysql
  hosts: all
  become: yes
  tasks:
    - name: Install mysql on Debian
      apt:
         name: mysql
         update_cache: yes
         cache_valid_time: 3600
         state: present
      when: ansible_distribution == "Debian"
  # - name: Run MYSQL commands
  # command: |
  #   mysql -p{{ mysql_root_password }} -ne "{{ item }}"
  # with_items:
  #   {{ mysql_root_password }}
