- name: Install mysql
  hosts: all
  become: yes

  tasks:
    - name: Run apt upgrade
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 432000
    - name: Add MySQL 8 Debian bullseye repository
      apt_repository:
        repo: deb http://archive.canonical.com/ubuntu hardy partner
        state: present
        filename: mysql_8_0.list
      when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11"

    - name: Install mysql on Debian
      apt:
        name:
          - mysql-server
          - mysql-devel
          - gcc
        state: latest
      when: ansible_distribution == "Debian" and ansible_distribution_major_version == "11"
  # - name: Run MYSQL commands
  # command: |
  #   mysql -p{{ mysql_root_password }} -ne "{{ item }}"
  # with_items:
  #   {{ mysql_root_password }}
