- name: checking service status
  hosts: all
  tasks:
  - name: checking service status
    command: systemctl status {{ service }}
    register: result
    ignore_errors: yes
  - name: showing report
    debug:
     var: result
